# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='owner',
        ),
    ]
